spring:
  application:
    name: Guessimate API
  threads:
    virtual:
      enabled: true
  datasource:
    name: guessimate
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/guessimate}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: guessimate-pool
      maximum-pool-size: 10
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      keepalive-time: 300000
      validation-timeout: 5000
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.xml
  jpa:
    open-in-view: false
otel:
  trace:
    enabled: ${OTEL_TRACE_ENABLED:false}
    endpoint: ${OTEL_TRACE_ENDPOINT:}

smd:
  eventstore:
    enabled: true

management:
  tracing:
    sampling:
      probability: 1
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always
